CREATE TABLE ZEPTO(
SKU_ID SERIAL PRIMARY KEY,
CATEGORY VARCHAR(120),
NAME VARCHAR(120) NOT NULL,
MRP NUMERIC(8,2),
DISCOUNTPERCENT NUMERIC(6,2),
AVAILABLEQUANTITY INTEGER,
DISCOUNTEDSELLINGPRICE NUMERIC(8,2),
WEIGHTINGMS INTEGER,
OUTOFSTOCK BOOLEAN,
QUANTITY INTEGER
);

SELECT * FROM ZEPTO;


-- DATA EXPLORATION

--TOTAL ROWS COUNT

SELECT COUNT(*) FROM ZEPTO;

--SAMPLE DATA

SELECT * FROM ZEPTO
LIMIT 10;

--NULL VALUES

SELECT * FROM ZEPTO 
WHERE NAME IS NULL OR
CATEGORY IS NULL OR
MRP IS NULL OR
DISCOUNTPERCENT IS NULL OR
DISCOUNTEDSELLINGPRICE IS NULL OR
WEIGHTINGMS IS NULL OR
AVAILABLEQUANTITY IS NULL OR
OUTOFSTOCK IS NULL OR
QUANTITY IS NULL ;

--DIFFERENT PRODUCT CATEGORIES

SELECT DISTINCT CATEGORY FROM ZEPTO
ORDER BY CATEGORY;

--COUNT OF PRODUCTS INSTOCK VS OUTOFSTOCK

SELECT OUTOFSTOCK,COUNT(SKU_ID) FROM ZEPTO
GROUP BY OUTOFSTOCK;

--PRODUCT NAMES MORE THAN ONCE

SELECT NAME,COUNT(SKU_ID) AS "NUMBER OF SKU"
FROM ZEPTO
GROUP BY NAME
HAVING COUNT(SKU_ID) > 1
ORDER BY COUNT(SKU_ID) DESC;

--DATA CLEANING

--PRODUCT WITH PRICE = 0

SELECT * FROM ZEPTO
WHERE MRP=0 OR DISCOUNTEDSELLINGPRICE=0;

--DELETION OF ERROR ROW

DELETE FROM ZEPTO
WHERE MRP=0;

--CONVERTING PAISE TO RUPEES

UPDATE ZEPTO
SET MRP=MRP/100.0,DISCOUNTEDSELLINGPRICE=DISCOUNTEDSELLINGPRICE/100.0;

--TOP 10 BEST-VALUE PRODUCTS BASED ON DISCOUNT PERCENTAGE

SELECT DISTINCT NAME,MRP,DISCOUNTPERCENT FROM ZEPTO
ORDER BY DISCOUNTPERCENT DESC
LIMIT 10;

--WHAT ARE THE PRODUCTS WITH HIGH MRP BUT OUTOFSTOCK

SELECT NAME,MRP
FROM ZEPTO
WHERE OUTOFSTOCK = TRUE
AND MRP>200
ORDER BY MRP DESC;

--CALCULATE ESTIMATED REVENUE FOR EACH CATEGORY

SELECT CATEGORY,
SUM((DISCOUNTEDSELLINGPRICE * AVAILABLEQUANTITY)) AS TOTAL_REVENUE
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY TOTAL_REVENUE;

--FIND ALL PRODUCTS WHERE MRP IS GREATER THAN 500 AND DISCOUNT IS LESS THAN 10%

SELECT DISTINCT NAME,MRP,DISCOUNTPERCENT
FROM ZEPTO
WHERE MRP > 500 AND DISCOUNTPERCENT < 10
ORDER BY  MRP DESC,DISCOUNTPERCENT DESC;

-- IDENTIFY TOP 5 CATEGORIES OFFERING THE HIGHEST AVERAGE DISCOUNT PERCENTAGE

SELECT CATEGORY,ROUND(AVG(DISCOUNTPERCENT),2) AS AVERAGE_DISCOUNT
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY AVERAGE_DISCOUNT DESC
LIMIT 5;

--FIND THE PRICE PER GRAM FOR PRODUCTS ABOVE 100G AND SORT BY BEST VALUE

SELECT DISTINCT NAME,WEIGHTINGMS,DISCOUNTEDSELLINGPRICE,
ROUND(DISCOUNTEDSELLINGPRICE/WEIGHTINGMS,2) AS PRICE_PER_GMS
FROM ZEPTO
WHERE WEIGHTINGMS >= 100
ORDER BY PRICE_PER_GMS;

--GROUP OF PRODUCTS INTO CATEGORIES LIKE LOW,MEDIUM AND BULK

SELECT DISTINCT NAME,WEIGHTINGMS,CASE WHEN WEIGHTINGMS <1000 THEN 'LOW'
WHEN WEIGHTINGMS <2000 THEN 'MEDIUM'
ELSE 'BULK'
END AS WEIGHT_CATEGORY
FROM ZEPTO;

--WHAT IS THE TOTAL INVENTORY WEIGHT PER CATEGORY
SELECT CATEGORY,
SUM(AVAILABLEQUANTITY * WEIGHTINGMS) AS TOTAL_INVENTORY_WEIGHT
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY TOTAL_INVENTORY_WEIGHT;


ALTER TABLE ZEPTO
ADD COLUMN DateAdded DATE;

UPDATE ZEPTO
SET DATEADDED = DATE '2021-01-01' + FLOOR(RANDOM() * (DATE'2023-01-01' - DATE '2021-01-01'))::INT;


SELECT * FROM ZEPTO;




